import { Schema } from "effect";

/**
 * Tailwind theme config — mirrors theme / theme.extend from tailwind.config.
 * Each key is optional; values are record-shaped (name → value or nested scale).
 * Individual keys can be replaced with stricter schemas when extending (e.g. theme-minimal).
 * @see https://v3.tailwindcss.com/docs/theme#configuration-reference
 */

/** Generic theme property: map of name to value (or nested). All theme keys use this shape; extend per-key when needed (e.g. theme-minimal). */
const TailwindThemeConfigPropertyRecordSchema = Schema.Record({
  key: Schema.String,
  value: Schema.Unknown,
});

const T = TailwindThemeConfigPropertyRecordSchema;

const TailwindThemeConfigSchema = Schema.Struct({
  accentColor: Schema.optional(T),
  animation: Schema.optional(T),
  aria: Schema.optional(T),
  aspectRatio: Schema.optional(T),
  backdropBlur: Schema.optional(T),
  backdropBrightness: Schema.optional(T),
  backdropContrast: Schema.optional(T),
  backdropGrayscale: Schema.optional(T),
  backdropHueRotate: Schema.optional(T),
  backdropInvert: Schema.optional(T),
  backdropOpacity: Schema.optional(T),
  backdropSaturate: Schema.optional(T),
  backdropSepia: Schema.optional(T),
  backgroundColor: Schema.optional(T),
  backgroundImage: Schema.optional(T),
  backgroundOpacity: Schema.optional(T),
  backgroundPosition: Schema.optional(T),
  backgroundSize: Schema.optional(T),
  blur: Schema.optional(T),
  borderColor: Schema.optional(T),
  borderOpacity: Schema.optional(T),
  borderRadius: Schema.optional(T),
  borderSpacing: Schema.optional(T),
  borderWidth: Schema.optional(T),
  boxShadow: Schema.optional(T),
  boxShadowColor: Schema.optional(T),
  brightness: Schema.optional(T),
  caretColor: Schema.optional(T),
  colors: Schema.optional(T),
  columns: Schema.optional(T),
  container: Schema.optional(T),
  content: Schema.optional(T),
  contrast: Schema.optional(T),
  cursor: Schema.optional(T),
  data: Schema.optional(T),
  divideColor: Schema.optional(T),
  divideOpacity: Schema.optional(T),
  divideWidth: Schema.optional(T),
  dropShadow: Schema.optional(T),
  fill: Schema.optional(T),
  flex: Schema.optional(T),
  flexBasis: Schema.optional(T),
  flexGrow: Schema.optional(T),
  flexShrink: Schema.optional(T),
  fontFamily: Schema.optional(T),
  fontSize: Schema.optional(T),
  fontWeight: Schema.optional(T),
  gap: Schema.optional(T),
  gradientColorStopPositions: Schema.optional(T),
  gradientColorStops: Schema.optional(T),
  grayscale: Schema.optional(T),
  gridAutoColumns: Schema.optional(T),
  gridAutoRows: Schema.optional(T),
  gridColumn: Schema.optional(T),
  gridColumnEnd: Schema.optional(T),
  gridColumnStart: Schema.optional(T),
  gridRow: Schema.optional(T),
  gridRowEnd: Schema.optional(T),
  gridRowStart: Schema.optional(T),
  gridTemplateColumns: Schema.optional(T),
  gridTemplateRows: Schema.optional(T),
  height: Schema.optional(T),
  hueRotate: Schema.optional(T),
  inset: Schema.optional(T),
  invert: Schema.optional(T),
  keyframes: Schema.optional(T),
  letterSpacing: Schema.optional(T),
  lineClamp: Schema.optional(T),
  lineHeight: Schema.optional(T),
  listStyleImage: Schema.optional(T),
  listStyleType: Schema.optional(T),
  margin: Schema.optional(T),
  maxHeight: Schema.optional(T),
  maxWidth: Schema.optional(T),
  minHeight: Schema.optional(T),
  minWidth: Schema.optional(T),
  objectPosition: Schema.optional(T),
  opacity: Schema.optional(T),
  order: Schema.optional(T),
  outlineColor: Schema.optional(T),
  outlineOffset: Schema.optional(T),
  outlineWidth: Schema.optional(T),
  padding: Schema.optional(T),
  placeholderColor: Schema.optional(T),
  placeholderOpacity: Schema.optional(T),
  ringColor: Schema.optional(T),
  ringOffsetColor: Schema.optional(T),
  ringOffsetWidth: Schema.optional(T),
  ringOpacity: Schema.optional(T),
  ringWidth: Schema.optional(T),
  rotate: Schema.optional(T),
  saturate: Schema.optional(T),
  scale: Schema.optional(T),
  screens: Schema.optional(T),
  scrollMargin: Schema.optional(T),
  scrollPadding: Schema.optional(T),
  sepia: Schema.optional(T),
  size: Schema.optional(T),
  skew: Schema.optional(T),
  space: Schema.optional(T),
  spacing: Schema.optional(T),
  stroke: Schema.optional(T),
  strokeWidth: Schema.optional(T),
  supports: Schema.optional(T),
  textColor: Schema.optional(T),
  textDecorationColor: Schema.optional(T),
  textDecorationThickness: Schema.optional(T),
  textIndent: Schema.optional(T),
  textOpacity: Schema.optional(T),
  textUnderlineOffset: Schema.optional(T),
  transformOrigin: Schema.optional(T),
  transitionDelay: Schema.optional(T),
  transitionDuration: Schema.optional(T),
  transitionProperty: Schema.optional(T),
  transitionTimingFunction: Schema.optional(T),
  translate: Schema.optional(T),
  width: Schema.optional(T),
  willChange: Schema.optional(T),
  zIndex: Schema.optional(T),
});

export { TailwindThemeConfigPropertyRecordSchema, TailwindThemeConfigSchema };
